AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable

Layout/EmptyLineBetweenDefs:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
